// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/model.proto

package ru.runov.server;

public final class TheMessages {
  private TheMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ru.runov.server.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG = 0;</code>
     */
    MSG(0),
    /**
     * <code>FILE = 1;</code>
     */
    FILE(1),
    /**
     * <code>DIR = 11;</code>
     */
    DIR(11),
    ;

    /**
     * <code>MSG = 0;</code>
     */
    public static final int MSG_VALUE = 0;
    /**
     * <code>FILE = 1;</code>
     */
    public static final int FILE_VALUE = 1;
    /**
     * <code>DIR = 11;</code>
     */
    public static final int DIR_VALUE = 11;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return MSG;
        case 1: return FILE;
        case 11: return DIR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ru.runov.server.TheMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ru.runov.server.Type)
  }

  public interface TheRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.runov.server.TheRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ru.runov.server.Type type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required .ru.runov.server.Type type = 1;</code>
     * @return The type.
     */
    ru.runov.server.TheMessages.Type getType();

    /**
     * <code>optional string requestMsg = 2;</code>
     * @return Whether the requestMsg field is set.
     */
    boolean hasRequestMsg();
    /**
     * <code>optional string requestMsg = 2;</code>
     * @return The requestMsg.
     */
    java.lang.String getRequestMsg();
    /**
     * <code>optional string requestMsg = 2;</code>
     * @return The bytes for requestMsg.
     */
    com.google.protobuf.ByteString
        getRequestMsgBytes();

    /**
     * <code>optional .ru.runov.server.FileMsg file = 3;</code>
     * @return Whether the file field is set.
     */
    boolean hasFile();
    /**
     * <code>optional .ru.runov.server.FileMsg file = 3;</code>
     * @return The file.
     */
    ru.runov.server.TheMessages.FileMsg getFile();
    /**
     * <code>optional .ru.runov.server.FileMsg file = 3;</code>
     */
    ru.runov.server.TheMessages.FileMsgOrBuilder getFileOrBuilder();
  }
  /**
   * Protobuf type {@code ru.runov.server.TheRequest}
   */
  public static final class TheRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.runov.server.TheRequest)
      TheRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TheRequest.newBuilder() to construct.
    private TheRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TheRequest() {
      type_ = 0;
      requestMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TheRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.runov.server.TheMessages.TheRequest.class, ru.runov.server.TheMessages.TheRequest.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .ru.runov.server.Type type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .ru.runov.server.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public ru.runov.server.TheMessages.Type getType() {
      @SuppressWarnings("deprecation")
      ru.runov.server.TheMessages.Type result = ru.runov.server.TheMessages.Type.valueOf(type_);
      return result == null ? ru.runov.server.TheMessages.Type.MSG : result;
    }

    public static final int REQUESTMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object requestMsg_;
    /**
     * <code>optional string requestMsg = 2;</code>
     * @return Whether the requestMsg field is set.
     */
    @java.lang.Override
    public boolean hasRequestMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string requestMsg = 2;</code>
     * @return The requestMsg.
     */
    @java.lang.Override
    public java.lang.String getRequestMsg() {
      java.lang.Object ref = requestMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestMsg = 2;</code>
     * @return The bytes for requestMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestMsgBytes() {
      java.lang.Object ref = requestMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_FIELD_NUMBER = 3;
    private ru.runov.server.TheMessages.FileMsg file_;
    /**
     * <code>optional .ru.runov.server.FileMsg file = 3;</code>
     * @return Whether the file field is set.
     */
    @java.lang.Override
    public boolean hasFile() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .ru.runov.server.FileMsg file = 3;</code>
     * @return The file.
     */
    @java.lang.Override
    public ru.runov.server.TheMessages.FileMsg getFile() {
      return file_ == null ? ru.runov.server.TheMessages.FileMsg.getDefaultInstance() : file_;
    }
    /**
     * <code>optional .ru.runov.server.FileMsg file = 3;</code>
     */
    @java.lang.Override
    public ru.runov.server.TheMessages.FileMsgOrBuilder getFileOrBuilder() {
      return file_ == null ? ru.runov.server.TheMessages.FileMsg.getDefaultInstance() : file_;
    }

    public static ru.runov.server.TheMessages.TheRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.runov.server.TheMessages.TheRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.runov.server.TheMessages.TheRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.runov.server.TheMessages.TheRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.runov.server.TheMessages.TheRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.runov.server.TheMessages.TheRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.runov.server.TheMessages.TheRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.runov.server.TheMessages.TheRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.runov.server.TheRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.runov.server.TheRequest)
        ru.runov.server.TheMessages.TheRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.runov.server.TheMessages.TheRequest.class, ru.runov.server.TheMessages.TheRequest.Builder.class);
      }

      // Construct using ru.runov.server.TheMessages.TheRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFileFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        requestMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (fileBuilder_ == null) {
          file_ = null;
        } else {
          fileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheRequest_descriptor;
      }

      @java.lang.Override
      public ru.runov.server.TheMessages.TheRequest getDefaultInstanceForType() {
        return ru.runov.server.TheMessages.TheRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ru.runov.server.TheMessages.TheRequest build() {
        ru.runov.server.TheMessages.TheRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.runov.server.TheMessages.TheRequest buildPartial() {
        ru.runov.server.TheMessages.TheRequest result = new ru.runov.server.TheMessages.TheRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestMsg_ = requestMsg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (fileBuilder_ == null) {
            result.file_ = file_;
          } else {
            result.file_ = fileBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .ru.runov.server.Type type = 1;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .ru.runov.server.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public ru.runov.server.TheMessages.Type getType() {
        @SuppressWarnings("deprecation")
        ru.runov.server.TheMessages.Type result = ru.runov.server.TheMessages.Type.valueOf(type_);
        return result == null ? ru.runov.server.TheMessages.Type.MSG : result;
      }
      /**
       * <code>required .ru.runov.server.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(ru.runov.server.TheMessages.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .ru.runov.server.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object requestMsg_ = "";
      /**
       * <code>optional string requestMsg = 2;</code>
       * @return Whether the requestMsg field is set.
       */
      public boolean hasRequestMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string requestMsg = 2;</code>
       * @return The requestMsg.
       */
      public java.lang.String getRequestMsg() {
        java.lang.Object ref = requestMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestMsg = 2;</code>
       * @return The bytes for requestMsg.
       */
      public com.google.protobuf.ByteString
          getRequestMsgBytes() {
        java.lang.Object ref = requestMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestMsg = 2;</code>
       * @param value The requestMsg to set.
       * @return This builder for chaining.
       */
      public Builder setRequestMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestMsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestMsg_ = getDefaultInstance().getRequestMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestMsg = 2;</code>
       * @param value The bytes for requestMsg to set.
       * @return This builder for chaining.
       */
      public Builder setRequestMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestMsg_ = value;
        onChanged();
        return this;
      }

      private ru.runov.server.TheMessages.FileMsg file_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.runov.server.TheMessages.FileMsg, ru.runov.server.TheMessages.FileMsg.Builder, ru.runov.server.TheMessages.FileMsgOrBuilder> fileBuilder_;
      /**
       * <code>optional .ru.runov.server.FileMsg file = 3;</code>
       * @return Whether the file field is set.
       */
      public boolean hasFile() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .ru.runov.server.FileMsg file = 3;</code>
       * @return The file.
       */
      public ru.runov.server.TheMessages.FileMsg getFile() {
        if (fileBuilder_ == null) {
          return file_ == null ? ru.runov.server.TheMessages.FileMsg.getDefaultInstance() : file_;
        } else {
          return fileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ru.runov.server.FileMsg file = 3;</code>
       */
      public Builder setFile(ru.runov.server.TheMessages.FileMsg value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          file_ = value;
          onChanged();
        } else {
          fileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ru.runov.server.FileMsg file = 3;</code>
       */
      public Builder setFile(
          ru.runov.server.TheMessages.FileMsg.Builder builderForValue) {
        if (fileBuilder_ == null) {
          file_ = builderForValue.build();
          onChanged();
        } else {
          fileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ru.runov.server.FileMsg file = 3;</code>
       */
      public Builder mergeFile(ru.runov.server.TheMessages.FileMsg value) {
        if (fileBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              file_ != null &&
              file_ != ru.runov.server.TheMessages.FileMsg.getDefaultInstance()) {
            file_ =
              ru.runov.server.TheMessages.FileMsg.newBuilder(file_).mergeFrom(value).buildPartial();
          } else {
            file_ = value;
          }
          onChanged();
        } else {
          fileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ru.runov.server.FileMsg file = 3;</code>
       */
      public Builder clearFile() {
        if (fileBuilder_ == null) {
          file_ = null;
          onChanged();
        } else {
          fileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .ru.runov.server.FileMsg file = 3;</code>
       */
      public ru.runov.server.TheMessages.FileMsg.Builder getFileBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ru.runov.server.FileMsg file = 3;</code>
       */
      public ru.runov.server.TheMessages.FileMsgOrBuilder getFileOrBuilder() {
        if (fileBuilder_ != null) {
          return fileBuilder_.getMessageOrBuilder();
        } else {
          return file_ == null ?
              ru.runov.server.TheMessages.FileMsg.getDefaultInstance() : file_;
        }
      }
      /**
       * <code>optional .ru.runov.server.FileMsg file = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.runov.server.TheMessages.FileMsg, ru.runov.server.TheMessages.FileMsg.Builder, ru.runov.server.TheMessages.FileMsgOrBuilder> 
          getFileFieldBuilder() {
        if (fileBuilder_ == null) {
          fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ru.runov.server.TheMessages.FileMsg, ru.runov.server.TheMessages.FileMsg.Builder, ru.runov.server.TheMessages.FileMsgOrBuilder>(
                  getFile(),
                  getParentForChildren(),
                  isClean());
          file_ = null;
        }
        return fileBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.runov.server.TheRequest)
    }

    // @@protoc_insertion_point(class_scope:ru.runov.server.TheRequest)
    private static final ru.runov.server.TheMessages.TheRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.runov.server.TheMessages.TheRequest();
    }

    public static ru.runov.server.TheMessages.TheRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TheRequest>
        PARSER = new com.google.protobuf.AbstractParser<TheRequest>() {
      @java.lang.Override
      public TheRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TheRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TheRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.runov.server.TheMessages.TheRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TheResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.runov.server.TheResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 code = 1;</code>
     * @return Whether the code field is set.
     */
    boolean hasCode();
    /**
     * <code>optional uint32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>optional string responseMsg = 2;</code>
     * @return Whether the responseMsg field is set.
     */
    boolean hasResponseMsg();
    /**
     * <code>optional string responseMsg = 2;</code>
     * @return The responseMsg.
     */
    java.lang.String getResponseMsg();
    /**
     * <code>optional string responseMsg = 2;</code>
     * @return The bytes for responseMsg.
     */
    com.google.protobuf.ByteString
        getResponseMsgBytes();
  }
  /**
   * Protobuf type {@code ru.runov.server.TheResponse}
   */
  public static final class TheResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.runov.server.TheResponse)
      TheResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TheResponse.newBuilder() to construct.
    private TheResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TheResponse() {
      responseMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TheResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.runov.server.TheMessages.TheResponse.class, ru.runov.server.TheMessages.TheResponse.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>optional uint32 code = 1;</code>
     * @return Whether the code field is set.
     */
    @java.lang.Override
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int RESPONSEMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object responseMsg_;
    /**
     * <code>optional string responseMsg = 2;</code>
     * @return Whether the responseMsg field is set.
     */
    @java.lang.Override
    public boolean hasResponseMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string responseMsg = 2;</code>
     * @return The responseMsg.
     */
    @java.lang.Override
    public java.lang.String getResponseMsg() {
      java.lang.Object ref = responseMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          responseMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string responseMsg = 2;</code>
     * @return The bytes for responseMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseMsgBytes() {
      java.lang.Object ref = responseMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static ru.runov.server.TheMessages.TheResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.runov.server.TheMessages.TheResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.runov.server.TheMessages.TheResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.runov.server.TheMessages.TheResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.runov.server.TheMessages.TheResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.runov.server.TheMessages.TheResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.TheResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.runov.server.TheMessages.TheResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.runov.server.TheMessages.TheResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.runov.server.TheResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.runov.server.TheResponse)
        ru.runov.server.TheMessages.TheResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.runov.server.TheMessages.TheResponse.class, ru.runov.server.TheMessages.TheResponse.Builder.class);
      }

      // Construct using ru.runov.server.TheMessages.TheResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.runov.server.TheMessages.internal_static_ru_runov_server_TheResponse_descriptor;
      }

      @java.lang.Override
      public ru.runov.server.TheMessages.TheResponse getDefaultInstanceForType() {
        return ru.runov.server.TheMessages.TheResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ru.runov.server.TheMessages.TheResponse build() {
        ru.runov.server.TheMessages.TheResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.runov.server.TheMessages.TheResponse buildPartial() {
        ru.runov.server.TheMessages.TheResponse result = new ru.runov.server.TheMessages.TheResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseMsg_ = responseMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>optional uint32 code = 1;</code>
       * @return Whether the code field is set.
       */
      @java.lang.Override
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional uint32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object responseMsg_ = "";
      /**
       * <code>optional string responseMsg = 2;</code>
       * @return Whether the responseMsg field is set.
       */
      public boolean hasResponseMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       * @return The responseMsg.
       */
      public java.lang.String getResponseMsg() {
        java.lang.Object ref = responseMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            responseMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       * @return The bytes for responseMsg.
       */
      public com.google.protobuf.ByteString
          getResponseMsgBytes() {
        java.lang.Object ref = responseMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       * @param value The responseMsg to set.
       * @return This builder for chaining.
       */
      public Builder setResponseMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        responseMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseMsg_ = getDefaultInstance().getResponseMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       * @param value The bytes for responseMsg to set.
       * @return This builder for chaining.
       */
      public Builder setResponseMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        responseMsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.runov.server.TheResponse)
    }

    // @@protoc_insertion_point(class_scope:ru.runov.server.TheResponse)
    private static final ru.runov.server.TheMessages.TheResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.runov.server.TheMessages.TheResponse();
    }

    public static ru.runov.server.TheMessages.TheResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TheResponse>
        PARSER = new com.google.protobuf.AbstractParser<TheResponse>() {
      @java.lang.Override
      public TheResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TheResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TheResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.runov.server.TheMessages.TheResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.runov.server.FileMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes fileBytes = 1;</code>
     * @return Whether the fileBytes field is set.
     */
    boolean hasFileBytes();
    /**
     * <code>optional bytes fileBytes = 1;</code>
     * @return The fileBytes.
     */
    com.google.protobuf.ByteString getFileBytes();

    /**
     * <code>optional string filename = 2;</code>
     * @return Whether the filename field is set.
     */
    boolean hasFilename();
    /**
     * <code>optional string filename = 2;</code>
     * @return The filename.
     */
    java.lang.String getFilename();
    /**
     * <code>optional string filename = 2;</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();
  }
  /**
   * Protobuf type {@code ru.runov.server.FileMsg}
   */
  public static final class FileMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.runov.server.FileMsg)
      FileMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileMsg.newBuilder() to construct.
    private FileMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileMsg() {
      fileBytes_ = com.google.protobuf.ByteString.EMPTY;
      filename_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.runov.server.TheMessages.internal_static_ru_runov_server_FileMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.runov.server.TheMessages.internal_static_ru_runov_server_FileMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.runov.server.TheMessages.FileMsg.class, ru.runov.server.TheMessages.FileMsg.Builder.class);
    }

    private int bitField0_;
    public static final int FILEBYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString fileBytes_;
    /**
     * <code>optional bytes fileBytes = 1;</code>
     * @return Whether the fileBytes field is set.
     */
    @java.lang.Override
    public boolean hasFileBytes() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes fileBytes = 1;</code>
     * @return The fileBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFileBytes() {
      return fileBytes_;
    }

    public static final int FILENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object filename_;
    /**
     * <code>optional string filename = 2;</code>
     * @return Whether the filename field is set.
     */
    @java.lang.Override
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string filename = 2;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string filename = 2;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static ru.runov.server.TheMessages.FileMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.runov.server.TheMessages.FileMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.FileMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.runov.server.TheMessages.FileMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.FileMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.runov.server.TheMessages.FileMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.FileMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.runov.server.TheMessages.FileMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.FileMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.runov.server.TheMessages.FileMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.runov.server.TheMessages.FileMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.runov.server.TheMessages.FileMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.runov.server.TheMessages.FileMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.runov.server.FileMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.runov.server.FileMsg)
        ru.runov.server.TheMessages.FileMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.runov.server.TheMessages.internal_static_ru_runov_server_FileMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.runov.server.TheMessages.internal_static_ru_runov_server_FileMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.runov.server.TheMessages.FileMsg.class, ru.runov.server.TheMessages.FileMsg.Builder.class);
      }

      // Construct using ru.runov.server.TheMessages.FileMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fileBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.runov.server.TheMessages.internal_static_ru_runov_server_FileMsg_descriptor;
      }

      @java.lang.Override
      public ru.runov.server.TheMessages.FileMsg getDefaultInstanceForType() {
        return ru.runov.server.TheMessages.FileMsg.getDefaultInstance();
      }

      @java.lang.Override
      public ru.runov.server.TheMessages.FileMsg build() {
        ru.runov.server.TheMessages.FileMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.runov.server.TheMessages.FileMsg buildPartial() {
        ru.runov.server.TheMessages.FileMsg result = new ru.runov.server.TheMessages.FileMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileBytes_ = fileBytes_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.filename_ = filename_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private com.google.protobuf.ByteString fileBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes fileBytes = 1;</code>
       * @return Whether the fileBytes field is set.
       */
      @java.lang.Override
      public boolean hasFileBytes() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes fileBytes = 1;</code>
       * @return The fileBytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getFileBytes() {
        return fileBytes_;
      }
      /**
       * <code>optional bytes fileBytes = 1;</code>
       * @param value The fileBytes to set.
       * @return This builder for chaining.
       */
      public Builder setFileBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes fileBytes = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileBytes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileBytes_ = getDefaultInstance().getFileBytes();
        onChanged();
        return this;
      }

      private java.lang.Object filename_ = "";
      /**
       * <code>optional string filename = 2;</code>
       * @return Whether the filename field is set.
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string filename = 2;</code>
       * @return The filename.
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string filename = 2;</code>
       * @return The bytes for filename.
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filename = 2;</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000002);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 2;</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        filename_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.runov.server.FileMsg)
    }

    // @@protoc_insertion_point(class_scope:ru.runov.server.FileMsg)
    private static final ru.runov.server.TheMessages.FileMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.runov.server.TheMessages.FileMsg();
    }

    public static ru.runov.server.TheMessages.FileMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FileMsg>
        PARSER = new com.google.protobuf.AbstractParser<FileMsg>() {
      @java.lang.Override
      public FileMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FileMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.runov.server.TheMessages.FileMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_runov_server_TheRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_runov_server_TheRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_runov_server_TheResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_runov_server_TheResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_runov_server_FileMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_runov_server_FileMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/model.proto\022\017ru.runov.server\"m\n\n" +
      "TheRequest\022#\n\004type\030\001 \002(\0162\025.ru.runov.serv" +
      "er.Type\022\022\n\nrequestMsg\030\002 \001(\t\022&\n\004file\030\003 \001(" +
      "\0132\030.ru.runov.server.FileMsg\"0\n\013TheRespon" +
      "se\022\014\n\004code\030\001 \001(\r\022\023\n\013responseMsg\030\002 \001(\t\".\n" +
      "\007FileMsg\022\021\n\tfileBytes\030\001 \001(\014\022\020\n\010filename\030" +
      "\002 \001(\t*\"\n\004Type\022\007\n\003MSG\020\000\022\010\n\004FILE\020\001\022\007\n\003DIR\020" +
      "\013B\017B\013TheMessagesH\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_runov_server_TheRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_runov_server_TheRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_runov_server_TheRequest_descriptor,
        new java.lang.String[] { "Type", "RequestMsg", "File", });
    internal_static_ru_runov_server_TheResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_runov_server_TheResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_runov_server_TheResponse_descriptor,
        new java.lang.String[] { "Code", "ResponseMsg", });
    internal_static_ru_runov_server_FileMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ru_runov_server_FileMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_runov_server_FileMsg_descriptor,
        new java.lang.String[] { "FileBytes", "Filename", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
